security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        utilisateur_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email  # Utilisation du champ email pour l'authentification des bénévoles


    firewalls:
        # Firewall pour les bénévoles
        main:
            pattern: ^/
            provider: utilisateur_provider
            form_login:
                login_path: login
                check_path: login
                default_target_path: /dashboard_redirect  # Redirection après login
            logout:
                path: /logout
                target: /
            stateless: false
            context: main




    access_control:


        # Deny authenticated users from accessing these pages
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/dashboard_benevole, roles: ROLE_BENEVOLE }
        - { path: ^/dashboard_association, roles: ROLE_ASSOCIATION }





