controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute



dashboard_redirect:
    path: /dashboard_redirect
    controller: App\Controller\SecurityController::redirectAfterLogin